### ISSUE TITLE
The text color for placeholder and also the selected item is not customizable, it is gray by default

### ISSUE THREAD

**Issue by brandyodhiambo** [Breens-Mbaka/Searchable-Dropdown-Menu-Jetpack-Compose#23]
The text color for placeholder and also the selected item is not customizable, it is gray by default

**Comment by Breens-Mbaka** [comment]
Hi @brandy-kay thanks for raising this issue;

1: Selected Item isn't customizable
If you want to customise this using the **colors** property in the **SearchableExpandedDropDownMenu**, see below example
`colors = TextFieldDefaults.outlinedTextFieldColors(Color.Red)`

2: Placeholder isn't customizable
Thanks for raising this issue and indeed this is true, will start working on this so be on the look out for the changes


Thanks @brandy-kay if you have any more issue feel free to let us know

**Comment by Breens-Mbaka** [comment]
@brandy-kay Unless you want to work on this issue ?

**Comment by joelkanyi** [comment]
Hey @Breens-Mbaka and @brandy-kay to customize the placeholder color, you can just do this:

```
SearchableExpandedDropDownMenu(
    ....
    colors = TextFieldDefaults.outlinedTextFieldColors(
            placeholderColor = Color.Black
    )
```

Let me know if this helps

**Comment by joelkanyi** [comment]
Then for customising the selected item color, I have realised that we forgot and used the `enable` property to disable the `OutlineTextField` other than just adding the property `isReadOnly`. In next lib version that I'm about to publish, this will be fixed.

Thanks in advance.

**Comment by Breens-Mbaka** [comment]
@JoelKanyi You're right, lemmie assign you this task then

> Hey @Breens-Mbaka and @brandy-kay to customize the placeholder color, you can just do this:
> 
> ```
> SearchableExpandedDropDownMenu(
>     ....
>     colors = TextFieldDefaults.outlinedTextFieldColors(
>             placeholderColor = Color.Black
>     )
> ```
> 
> Let me know if this helps
Yes this is the way to customise the placeholder ✅

**Comment by joelkanyi** [comment]
Fixed
