### ISSUE TITLE
How can we make the lib work with Material 3

### ISSUE THREAD

**Issue by joelkanyi** [Breens-Mbaka/Searchable-Dropdown-Menu-Jetpack-Compose#24]

**Comment by Breens-Mbaka** [comment]
Hi @JoelKanyi this is a great idea, what are your suggestion ? Since I've only seen migration from Material 2 to Material 3 but will do my research and see how this can be done. In the meantime if you have any ideas you can feel free to let me know

**Comment by joelkanyi** [comment]
You can assign this issue to me, I will refactor the library with Material 3

**Comment by joelkanyi** [comment]
Done
