### ISSUE TITLE
The Dropdown only opens when you click on the icon, when you click other parts of the ` Searchable-Dropdown-Menu-Jetpack-Compose` nothing happens

### ISSUE THREAD

**Issue by joelkanyi** [Breens-Mbaka/Searchable-Dropdown-Menu-Jetpack-Compose#30]
The Dropdown only opens when you click on the icon, when you click other parts of the ` Searchable-Dropdown-Menu-Jetpack-Compose` nothing happens.

**Comment by Breens-Mbaka** [comment]
Awesome work 🎉 @JoelKanyi
